//! FIPS 204 section 6: the internal functions, with their seed supplied
//! by the caller.
//!
//! ⛔ FOR TESTING ONLY, and public only with the `internal` feature. FIPS
//! 204 section 6: these interfaces "should not be made available to
//! applications, as any random values required for key generation and
//! signature generation shall be generated by the cryptographic module".
//! Whoever chooses `xi` knows the private key. Applications use
//! [`crate::key_gen`], which draws it from the OS.
//!
//! They exist because NIST's ACVP vectors supply `xi` directly, so this is
//! the form that can be checked byte-exactly.

use macula_keccak::Shake256;
use zeroize::Zeroizing;

use crate::encode::{pk_encode, sk_encode};
use crate::poly::{add, from_signed, multiply_add_ntt, ntt, ntt_inverse, power2round, Poly, N};
use crate::sample::{expand_a, expand_s, K_MAX, L_MAX};
use crate::ParameterSet;

/// FIPS 204 Algorithm 6, `ML-DSA.KeyGen_internal`.
///
/// Returns `(pk, sk)`. `sk` wipes itself when dropped, and so does every
/// secret intermediate: the seeds `rho'` and `K`, `s1`, `s2`, `t` and `t0`.
pub fn key_gen(p: ParameterSet, xi: &[u8; 32]) -> (Vec<u8>, Zeroizing<Vec<u8>>) {
    // (rho, rho', K) = H(xi || k || l, 128). The parameter bytes separate
    // the expansions of one seed under different parameter sets.
    let mut seeds = Zeroizing::new([0u8; 128]);
    let mut h = Shake256::new();
    h.update(xi);
    h.update(&[p.k as u8, p.l as u8]);
    h.finalize_xof().read(&mut *seeds);
    let rho: [u8; 32] = seeds[..32].try_into().expect("32 bytes");
    let mut rho_prime = Zeroizing::new([0u8; 64]);
    rho_prime.copy_from_slice(&seeds[32..96]);
    let mut key = Zeroizing::new([0u8; 32]);
    key.copy_from_slice(&seeds[96..]);

    let a_hat = expand_a(&rho, p);
    let mut s1 = Zeroizing::new([[0i32; N]; L_MAX]);
    let mut s2 = Zeroizing::new([[0i32; N]; K_MAX]);
    expand_s(&mut s1, &mut s2, &rho_prime, p);

    // t = NTT^-1(A_hat o NTT(s1)) + s2, then (t1, t0) = Power2Round(t).
    let mut s1_hat = Zeroizing::new(*s1);
    for poly in s1_hat.iter_mut().take(p.l) {
        ntt(poly);
    }
    let mut t1 = [[0i32; N]; K_MAX];
    let mut t0 = Zeroizing::new([[0i32; N]; K_MAX]);
    let mut t: Zeroizing<Poly> = Zeroizing::new([0i32; N]);
    for r in 0..p.k {
        t.fill(0);
        for s in 0..p.l {
            multiply_add_ntt(&mut t, &a_hat[r][s], &s1_hat[s]);
        }
        ntt_inverse(&mut t);
        for i in 0..N {
            let (high, low) = power2round(add(t[i], s2[r][i]));
            t1[r][i] = high;
            t0[r][i] = from_signed(low);
        }
    }

    let mut pk = vec![0u8; p.public_key_len()];
    pk_encode(&mut pk, &rho, &t1, p);
    // tr = H(pk, 64)
    let mut tr = [0u8; 64];
    let mut h = Shake256::new();
    h.update(&pk);
    h.finalize_xof().read(&mut tr);

    let mut sk = Zeroizing::new(vec![0u8; p.private_key_len()]);
    sk_encode(&mut sk, &rho, &key, &tr, &s1, &s2, &t0, p);
    (pk, sk)
}
