//! FIPS 204 section 6: the internal functions, with their randomness
//! supplied by the caller.
//!
//! ⛔ FOR TESTING ONLY, and public only with the `internal` feature. FIPS
//! 204 section 6: these interfaces "should not be made available to
//! applications, as any random values required for key generation and
//! signature generation shall be generated by the cryptographic module".
//! Whoever chooses `xi` knows the private key, and whoever chooses `rnd`
//! makes signing deterministic. Applications use [`crate::key_gen`] and
//! [`crate::sign`], which draw both from the OS.
//!
//! They exist because NIST's ACVP vectors supply `xi` and `rnd` directly,
//! so this is the form that can be checked byte-exactly.
//!
//! Verification has no randomness and FIPS 204 does not restrict it; it
//! is here because NIST's vectors test it on `M'` and on an externally
//! computed `mu`. Applications use [`crate::verify`], which formats `M'`
//! from their message and context.

use macula_keccak::Shake256;
use zeroize::{Zeroize, Zeroizing};

use crate::encode::{
    pk_decode, pk_encode, sig_decode, sig_encode, sk_decode, sk_encode, w1_encode_into,
};
use crate::poly::{
    add, centered_abs, from_signed, high_bits, low_bits, make_hint, multiply_add_ntt, ntt,
    ntt_inverse, power2round, sub, use_hint, Poly, N,
};
use crate::sample::{expand_a, expand_mask, expand_s, sample_in_ball, K_MAX, L_MAX};
use crate::{Error, ParameterSet, PrivateKey, D};

/// FIPS 204 Algorithm 6, `ML-DSA.KeyGen_internal`.
///
/// Returns `(pk, sk)`. `sk` wipes itself when dropped, and so does every
/// secret intermediate: the seeds `rho'` and `K`, `s1`, `s2`, `t` and `t0`.
pub fn key_gen(p: ParameterSet, xi: &[u8; 32]) -> (Vec<u8>, Zeroizing<Vec<u8>>) {
    // (rho, rho', K) = H(xi || k || l, 128). The parameter bytes separate
    // the expansions of one seed under different parameter sets.
    let mut seeds = Zeroizing::new([0u8; 128]);
    let mut h = Shake256::new();
    h.update(xi);
    h.update(&[p.k as u8, p.l as u8]);
    h.finalize_xof().read(&mut *seeds);
    let rho: [u8; 32] = seeds[..32].try_into().expect("32 bytes");
    let mut rho_prime = Zeroizing::new([0u8; 64]);
    rho_prime.copy_from_slice(&seeds[32..96]);
    let mut key = Zeroizing::new([0u8; 32]);
    key.copy_from_slice(&seeds[96..]);

    let a_hat = expand_a(&rho, p);
    let mut s1 = Zeroizing::new([[0i32; N]; L_MAX]);
    let mut s2 = Zeroizing::new([[0i32; N]; K_MAX]);
    expand_s(&mut s1, &mut s2, &rho_prime, p);

    // t = NTT^-1(A_hat o NTT(s1)) + s2, then (t1, t0) = Power2Round(t).
    let mut s1_hat = Zeroizing::new(*s1);
    for poly in s1_hat.iter_mut().take(p.l) {
        ntt(poly);
    }
    let mut t1 = [[0i32; N]; K_MAX];
    let mut t0 = Zeroizing::new([[0i32; N]; K_MAX]);
    let mut t: Zeroizing<Poly> = Zeroizing::new([0i32; N]);
    for r in 0..p.k {
        t.fill(0);
        for s in 0..p.l {
            multiply_add_ntt(&mut t, &a_hat[r][s], &s1_hat[s]);
        }
        ntt_inverse(&mut t);
        for i in 0..N {
            let (high, low) = power2round(add(t[i], s2[r][i]));
            t1[r][i] = high;
            t0[r][i] = from_signed(low);
        }
    }

    let mut pk = vec![0u8; p.public_key_len()];
    pk_encode(&mut pk, &rho, &t1, p);
    // tr = H(pk, 64)
    let mut tr = [0u8; 64];
    let mut h = Shake256::new();
    h.update(&pk);
    h.finalize_xof().read(&mut tr);

    let mut sk = Zeroizing::new(vec![0u8; p.private_key_len()]);
    sk_encode(&mut sk, &rho, &key, &tr, &s1, &s2, &t0, p);
    (pk, sk)
}

/// FIPS 204 Algorithm 8, `ML-DSA.Verify_internal`, on the formatted
/// message `M'`.
#[cfg(feature = "internal")]
pub fn verify(p: ParameterSet, pk: &[u8], m_prime: &[u8], sig: &[u8]) -> bool {
    verify_absorbing(p, pk, sig, |h| h.update(m_prime))
}

/// FIPS 204 Algorithm 8 with `mu` computed elsewhere, as line 7 allows:
/// `mu = H(tr || M', 64)`.
#[cfg(feature = "internal")]
pub fn verify_mu(p: ParameterSet, pk: &[u8], mu: &[u8; 64], sig: &[u8]) -> bool {
    lengths_are_the_standards(p, pk, sig) && verify_given_mu(p, pk, mu, sig)
}

/// FIPS 204 section 3.6.2's length rule: a public key or signature of any
/// other length is refused, with `false`.
fn lengths_are_the_standards(p: ParameterSet, pk: &[u8], sig: &[u8]) -> bool {
    pk.len() == p.public_key_len() && sig.len() == p.signature_len()
}

/// Algorithm 8 with `M'` supplied as whatever `absorb` feeds into
/// `H(tr || ...)`: `M'` itself, or for [`crate::verify`] the pieces
/// `0 || |ctx| || ctx || M`, absorbed without being concatenated.
pub(crate) fn verify_absorbing(
    p: ParameterSet,
    pk: &[u8],
    sig: &[u8],
    absorb: impl FnOnce(&mut Shake256),
) -> bool {
    if !lengths_are_the_standards(p, pk, sig) {
        return false;
    }
    let mut tr = [0u8; 64];
    let mut h = Shake256::new();
    h.update(pk);
    h.finalize_xof().read(&mut tr);
    let mut h = Shake256::new();
    h.update(&tr);
    absorb(&mut h);
    let mut mu = [0u8; 64];
    h.finalize_xof().read(&mut mu);
    verify_given_mu(p, pk, &mu, sig)
}

/// Algorithm 8, lines 1 to 13, once `mu` is known. Everything here is
/// public: the key, the signature and the message.
fn verify_given_mu(p: ParameterSet, pk: &[u8], mu: &[u8; 64], sig: &[u8]) -> bool {
    let (rho, t1) = pk_decode(pk, p);
    let Some(s) = sig_decode(sig, p) else {
        return false;
    };
    // ||z||_inf < gamma1 - beta. Checked first: it needs no arithmetic.
    let bound = p.gamma1 - p.beta();
    if s.z
        .iter()
        .take(p.l)
        .any(|poly| poly.iter().any(|&c| centered_abs(c) >= bound))
    {
        return false;
    }
    let a_hat = expand_a(&rho, p);
    let mut c_hat = sample_in_ball(s.c_tilde, p.tau);
    ntt(&mut c_hat);
    let mut z_hat = s.z;
    for poly in z_hat.iter_mut().take(p.l) {
        ntt(poly);
    }
    // w'_Approx = NTT^-1(A_hat o NTT(z) - NTT(c) o NTT(t1 * 2^d)), then
    // w'_1 = UseHint(h, w'_Approx).
    let mut w1 = Box::new([[0i32; N]; K_MAX]);
    for r in 0..p.k {
        let mut w = [0i32; N];
        for s_ in 0..p.l {
            multiply_add_ntt(&mut w, &a_hat[r][s_], &z_hat[s_]);
        }
        let mut t1_hat: Poly = [0i32; N];
        for (t, &c) in t1_hat.iter_mut().zip(t1[r].iter()) {
            *t = c << D;
        }
        ntt(&mut t1_hat);
        let mut ct1 = [0i32; N];
        multiply_add_ntt(&mut ct1, &c_hat, &t1_hat);
        for (wi, ci) in w.iter_mut().zip(ct1.iter()) {
            *wi = sub(*wi, *ci);
        }
        ntt_inverse(&mut w);
        for i in 0..N {
            w1[r][i] = use_hint(s.h[r][i], w[i], p.gamma2);
        }
    }
    // c~' = H(mu || w1Encode(w'_1), lambda / 4), compared with c~.
    let mut h = Shake256::new();
    h.update(mu);
    w1_encode_into(&mut h, &w1, p);
    let mut c_tilde = [0u8; 64];
    let c_len = p.lambda / 4;
    h.finalize_xof().read(&mut c_tilde[..c_len]);
    c_tilde[..c_len] == *s.c_tilde
}

/// FIPS 204 Algorithm 7, `ML-DSA.Sign_internal`, on the formatted message
/// `M'`, with the signing randomness `rnd` supplied: all zeros is the
/// deterministic variant.
#[cfg(feature = "internal")]
pub fn sign(
    p: ParameterSet,
    sk: PrivateKey,
    m_prime: &[u8],
    rnd: &[u8; 32],
) -> Result<Vec<u8>, Error> {
    sign_absorbing(p, sk, rnd, |h| h.update(m_prime))
}

/// FIPS 204 Algorithm 7 with `mu` computed elsewhere, as line 6 allows.
#[cfg(feature = "internal")]
pub fn sign_mu(
    p: ParameterSet,
    sk: PrivateKey,
    mu: &[u8; 64],
    rnd: &[u8; 32],
) -> Result<Vec<u8>, Error> {
    with_expanded(p, sk, |sk| {
        sign_given_mu(p, sk, mu, rnd, p.gamma1 - p.beta())
    })
}

/// FIPS 204 Algorithm 2, `ML-DSA.Sign`, with `rnd` supplied rather than
/// drawn: `M' = 0 || |ctx| || ctx || message`, absorbed in pieces.
/// [`crate::sign`] is this with `rnd` from the OS.
pub fn sign_message(
    p: ParameterSet,
    sk: PrivateKey,
    message: &[u8],
    context: &[u8],
    rnd: &[u8; 32],
) -> Result<Vec<u8>, Error> {
    crate::context_fits(context)?;
    sign_absorbing(p, sk, rnd, |h| {
        h.update(&[0, context.len() as u8]);
        h.update(context);
        h.update(message);
    })
}

/// The expanded private key, whichever form it arrived in. A seed is
/// expanded by `KeyGen_internal`, as FIPS 204 section 3.6.3 allows a
/// private key to be stored as its seed; the expansion wipes itself.
fn with_expanded<T>(
    p: ParameterSet,
    sk: PrivateKey,
    f: impl FnOnce(&[u8]) -> T,
) -> Result<T, Error> {
    match sk {
        PrivateKey::Expanded(bytes) if bytes.len() == p.private_key_len() => Ok(f(bytes)),
        PrivateKey::Expanded(_) => Err(Error::WrongLength),
        PrivateKey::Seed(seed) => {
            let (_, expanded) = key_gen(p, seed);
            Ok(f(&expanded))
        }
    }
}

/// Algorithm 7 with `M'` supplied as whatever `absorb` feeds into
/// `mu = H(tr || ..., 64)`.
fn sign_absorbing(
    p: ParameterSet,
    sk: PrivateKey,
    rnd: &[u8; 32],
    absorb: impl FnOnce(&mut Shake256),
) -> Result<Vec<u8>, Error> {
    with_expanded(p, sk, |sk| {
        let mut h = Shake256::new();
        h.update(&sk[64..128]);
        absorb(&mut h);
        let mut mu = [0u8; 64];
        h.finalize_xof().read(&mut mu);
        sign_given_mu(p, sk, &mu, rnd, p.gamma1 - p.beta())
    })
}

/// The largest centered absolute value among the first `n` polynomials:
/// every coefficient is visited, so the time does not depend on where a
/// large one sits. Only the comparison of the result is a branch, and
/// FIPS 204's rejection loop is allowed to vary with it.
fn norm<const M: usize>(v: &[Poly; M], n: usize) -> i32 {
    let mut max = 0;
    for poly in v.iter().take(n) {
        for &c in poly.iter() {
            let a = centered_abs(c);
            max ^= (max ^ a) & ((max - a) >> 31);
        }
    }
    max
}

/// Algorithm 7, line 23: `||z|| < gamma1 - beta` (the bound passed in) and
/// `||r0|| < gamma2 - beta`, or the attempt is rejected.
fn z_and_r0_releasable(z_norm: i32, r0_norm: i32, z_bound: i32, p: ParameterSet) -> bool {
    z_norm < z_bound && r0_norm < p.gamma2 - p.beta()
}

/// Algorithm 7, line 28: `||c t0|| < gamma2` and at most `omega` ones in
/// the hint, or the attempt is rejected.
///
/// ⚠ The `c t0` bound is unreachable by an honest key at ML-DSA-65 and -87,
/// where `tau * 2^12` is below `gamma2`, and about six standard deviations
/// away at ML-DSA-44, so no signature, NIST's or ours, exercises it. The
/// unit tests hold this function to both boundaries instead.
fn hint_releasable(ct0_norm: i32, ones: usize, p: ParameterSet) -> bool {
    ct0_norm < p.gamma2 && ones <= p.omega
}

/// Algorithm 7, lines 1 to 34, once `mu` is known.
///
/// `z_bound` is `gamma1 - beta` in every signature this crate releases.
/// It is a parameter only so the unit tests below can make a signature
/// whose `z` breaks the bound while everything else holds, the one input
/// that can test verification's norm check.
///
/// Every secret and every rejected attempt is wiped: the key's `K`, `s1`,
/// `s2`, `t0` and their NTTs, `rho''`, and each iteration's `y`, `w`,
/// `cs2`, `ct0` and `z`. A rejected `z` must never be released: it leaks
/// the key.
fn sign_given_mu(
    p: ParameterSet,
    sk: &[u8],
    mu: &[u8; 64],
    rnd: &[u8; 32],
    z_bound: i32,
) -> Vec<u8> {
    let mut s1 = Zeroizing::new([[0i32; N]; L_MAX]);
    let mut s2 = Zeroizing::new([[0i32; N]; K_MAX]);
    let mut t0 = Zeroizing::new([[0i32; N]; K_MAX]);
    let (rho, key, _tr) = sk_decode(sk, p, &mut s1, &mut s2, &mut t0);
    // From here on s1, s2 and t0 hold their NTTs.
    for poly in s1.iter_mut().take(p.l) {
        ntt(poly);
    }
    for poly in s2.iter_mut().take(p.k).chain(t0.iter_mut().take(p.k)) {
        ntt(poly);
    }
    let a_hat = expand_a(&rho, p);

    // rho'' = H(K || rnd || mu, 64), absorbed in pieces: K is never copied.
    let mut rho_pp = Zeroizing::new([0u8; 64]);
    let mut h = Shake256::new();
    h.update(&*key);
    h.update(rnd);
    h.update(mu);
    h.finalize_xof().read(&mut *rho_pp);

    let c_len = p.lambda / 4;
    let mut y = Zeroizing::new([[0i32; N]; L_MAX]);
    let mut y_hat = Zeroizing::new([[0i32; N]; L_MAX]);
    let mut z = Zeroizing::new([[0i32; N]; L_MAX]);
    let mut w = Zeroizing::new([[0i32; N]; K_MAX]);
    let mut w1 = Zeroizing::new([[0i32; N]; K_MAX]);
    let mut cs2 = Zeroizing::new([[0i32; N]; K_MAX]);
    let mut r0 = Zeroizing::new([[0i32; N]; K_MAX]);
    let mut ct0 = Zeroizing::new([[0i32; N]; K_MAX]);
    let mut hint = Zeroizing::new([[0i32; N]; K_MAX]);
    let mut kappa: u16 = 0;
    loop {
        expand_mask(&mut y, &rho_pp, kappa, p);
        kappa = kappa.wrapping_add(p.l as u16);

        // w = NTT^-1(A_hat o NTT(y)), w1 = HighBits(w).
        *y_hat = *y;
        for poly in y_hat.iter_mut().take(p.l) {
            ntt(poly);
        }
        for r in 0..p.k {
            w[r].fill(0);
            for s in 0..p.l {
                multiply_add_ntt(&mut w[r], &a_hat[r][s], &y_hat[s]);
            }
            ntt_inverse(&mut w[r]);
            for i in 0..N {
                w1[r][i] = high_bits(w[r][i], p.gamma2);
            }
        }

        // c~ = H(mu || w1Encode(w1), lambda / 4), c = SampleInBall(c~).
        let mut c_tilde = [0u8; 64];
        let mut h = Shake256::new();
        h.update(mu);
        w1_encode_into(&mut h, &w1, p);
        h.finalize_xof().read(&mut c_tilde[..c_len]);
        let mut c_hat = sample_in_ball(&c_tilde[..c_len], p.tau);
        ntt(&mut c_hat);

        // z = y + c s1, r0 = LowBits(w - c s2).
        for s in 0..p.l {
            let mut cs1 = [0i32; N];
            multiply_add_ntt(&mut cs1, &c_hat, &s1[s]);
            ntt_inverse(&mut cs1);
            for i in 0..N {
                z[s][i] = add(y[s][i], cs1[i]);
            }
            cs1.zeroize();
        }
        for r in 0..p.k {
            cs2[r].fill(0);
            multiply_add_ntt(&mut cs2[r], &c_hat, &s2[r]);
            ntt_inverse(&mut cs2[r]);
            for i in 0..N {
                r0[r][i] = from_signed(low_bits(sub(w[r][i], cs2[r][i]), p.gamma2));
            }
        }
        if !z_and_r0_releasable(norm(&z, p.l), norm(&r0, p.k), z_bound, p) {
            continue;
        }

        // h = MakeHint(-c t0, w - c s2 + c t0).
        let mut ones = 0;
        for r in 0..p.k {
            ct0[r].fill(0);
            multiply_add_ntt(&mut ct0[r], &c_hat, &t0[r]);
            ntt_inverse(&mut ct0[r]);
            for i in 0..N {
                let minus_ct0 = sub(0, ct0[r][i]);
                let base = add(sub(w[r][i], cs2[r][i]), ct0[r][i]);
                hint[r][i] = make_hint(minus_ct0, base, p.gamma2);
                ones += hint[r][i] as usize;
            }
        }
        if !hint_releasable(norm(&ct0, p.k), ones, p) {
            continue;
        }
        return sig_encode(&c_tilde[..c_len], &z, &hint, p);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ML_DSA_44, ML_DSA_65, ML_DSA_87};

    fn mu_of(pk: &[u8], message: &[u8]) -> [u8; 64] {
        let mut tr = [0u8; 64];
        let mut h = Shake256::new();
        h.update(pk);
        h.finalize_xof().read(&mut tr);
        let mut h = Shake256::new();
        h.update(&tr);
        h.update(message);
        let mut mu = [0u8; 64];
        h.finalize_xof().read(&mut mu);
        mu
    }

    /// ⛔ VERIFICATION'S NORM CHECK, the one input that can test it: a
    /// signature whose `z` breaks `gamma1 - beta` while its commitment,
    /// hint and everything else hold. Every NIST "modified z" case is
    /// rejected by the commitment comparison first, so without this test
    /// removing the norm check passes every vector.
    ///
    /// The signer is run with its own `z` bound raised to `gamma1`, which
    /// keeps `z` encodable, until it emits a signature the real bound
    /// would have rejected. The same key's ordinary signature is the
    /// positive control.
    #[test]
    fn verification_refuses_a_z_past_the_bound_even_with_a_matching_commitment() {
        let p = ML_DSA_65;
        let (pk, sk) = key_gen(p, &[3u8; 32]);
        let mut found = 0;
        for i in 0u32..400 {
            let message = i.to_le_bytes();
            let mu = mu_of(&pk, &message);
            let sig = sign_given_mu(p, &sk, &mu, &[0u8; 32], p.gamma1);
            let s = sig_decode(&sig, p).expect("a well-formed signature");
            if norm(&s.z, p.l) < p.gamma1 - p.beta() {
                assert!(
                    verify_mu_unchecked(p, &pk, &mu, &sig),
                    "message {i}: control"
                );
                continue;
            }
            assert!(
                !verify_mu_unchecked(p, &pk, &mu, &sig),
                "message {i}: a z past gamma1 - beta was accepted"
            );
            found += 1;
            if found == 3 {
                return;
            }
        }
        panic!("400 signatures gave only {found} with z past the bound: nothing was tested");
    }

    /// Algorithm 8 with the length rule applied, for the tests above:
    /// `verify_mu` is compiled only with the `internal` feature.
    fn verify_mu_unchecked(p: ParameterSet, pk: &[u8], mu: &[u8; 64], sig: &[u8]) -> bool {
        lengths_are_the_standards(p, pk, sig) && verify_given_mu(p, pk, mu, sig)
    }

    /// ⛔ HINTBITUNPACK'S "COUNT RUNNING BACKWARDS" REFUSAL. It can only be
    /// planted without changing the hint on a polynomial with no hints
    /// after one with some, and none of NIST's valid signatures has one. So
    /// this signs until one does, lowers that polynomial's count below its
    /// predecessor's, and requires refusal. Skipping the check, the
    /// malformed hint decodes to the original, so nothing else rejects it.
    #[test]
    fn verification_refuses_a_hint_count_running_backwards() {
        let p = ML_DSA_87;
        let (pk, sk) = key_gen(p, &[5u8; 32]);
        let (omega, k) = (p.omega, p.k);
        for i in 0u32..2000 {
            let message = i.to_le_bytes();
            let mu = mu_of(&pk, &message);
            let sig = sign_given_mu(p, &sk, &mu, &[0u8; 32], p.gamma1 - p.beta());
            let y = sig.len() - (omega + k);
            let count = |i: usize| sig[y + omega + i] as usize;
            let Some(i) = (1..k).find(|&i| count(i) == count(i - 1) && count(i) > 0) else {
                continue;
            };
            assert!(verify_mu_unchecked(p, &pk, &mu, &sig), "control");
            let mut bad = sig.clone();
            bad[y + omega + i] -= 1;
            assert!(
                !verify_mu_unchecked(p, &pk, &mu, &bad),
                "a hint count running backwards was accepted"
            );
            return;
        }
        panic!("2000 signatures without a hint-free polynomial: nothing was tested");
    }

    /// Algorithm 7, line 23, at its boundaries in every parameter set:
    /// one below each bound is released, the bound itself is not.
    #[test]
    fn z_and_r0_are_released_only_below_their_bounds() {
        for p in [ML_DSA_44, ML_DSA_65, ML_DSA_87] {
            let zb = p.gamma1 - p.beta();
            let rb = p.gamma2 - p.beta();
            assert!(z_and_r0_releasable(zb - 1, rb - 1, zb, p), "{}", p.name);
            assert!(
                !z_and_r0_releasable(zb, rb - 1, zb, p),
                "{}: z at its bound",
                p.name
            );
            assert!(
                !z_and_r0_releasable(zb - 1, rb, zb, p),
                "{}: r0 at its bound",
                p.name
            );
        }
    }

    /// Algorithm 7, line 28, at its boundaries in every parameter set. The
    /// `c t0` bound is reached by no real signature (see
    /// `hint_releasable`), so this is its only test.
    #[test]
    fn a_hint_is_released_only_below_its_bounds() {
        for p in [ML_DSA_44, ML_DSA_65, ML_DSA_87] {
            assert!(hint_releasable(p.gamma2 - 1, p.omega, p), "{}", p.name);
            assert!(
                !hint_releasable(p.gamma2, p.omega, p),
                "{}: c t0 at gamma2",
                p.name
            );
            assert!(
                !hint_releasable(p.gamma2 - 1, p.omega + 1, p),
                "{}: omega + 1 ones",
                p.name
            );
        }
    }
}
